Add snapshot testing for generator modules with Verify
atc-net/atc-rest-api-generator pull request #87
Opened 2021-02-08 15:35 UTC by TomMalow

This PR adds [snapshot testing](https://www.sitepen.com/blog/snapshot-testing-benefits-and-drawbacks) to the output of ATC Generator.

Snapshot testing is done through [Verify package](https://github.com/VerifyTests/Verify) which is setup to take in a .yaml OpenApi spec file and generate a C# output file. The test setup currently only supports spec files that would generate a single file.

Currently the new test handles the following syntnx generators:
 - `SyntaxGeneratorContractInterface`
 - `SyntaxGeneratorContractModel`
 - `SyntaxGeneratorContractParameter`
 - `SyntaxGeneratorContractResult`
 - `SyntaxGeneratorEndpointControllers`

The Verify package uses two type of files to compare the snapshot.
- `.verified.cs` is the base truth to compare against. These files are stored in the code base.
- `.received.cs` is the output of a failed test  where the received file did not match the verified file. These files are git ignored.

Executing a single test that fails will open vs diff tool to compare between the `.verified.cs` and the `.received.cs` file.

# Adding a new test
Adding a new test is done by simply adding a new openapi spec .yaml file to the relevant folder for a given syntax generator. This file will need to be reduced to only contain the minimal spec necessary to generate a single output file. Some of the test has additional asserts to verify that the spec.

The first time the test is run the test will fail and a `.received.cs` file is generated. The Verify package will fill your clipboard with a command line snippet to rename the received file to a verified file. This makes it a bit easier to add the output as a new base truth to compare against.

# Updating all verified file
If a intentional change to ATC generator would change the output of multiple verified files, resulting in multiple failed test. Then a setting can be added to Verify setting to accept all new output and update all `.verified.cs` files.
Add following line to `VerifySettings` setup in `SyntaxGeneratorTestBase.cs`
```csharp
var settings = new VerifySettings();
settings.AutoVerify();
```
Remember to remove this again. Otherwise all changes will be accepted and not test will fail.

# Additional
A tiny whitespace bug is also part of this PR.

2021-02-09 22:37 UTC, davidkallesen requested changes

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractInterfaceTest.cs
> +            Assert.NotNull(specFile?.FilePath);
```suggestion
            Assert.NotNull(specFile.FilePath);
```

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractModelTest.cs
> +            Assert.NotNull(specFile?.FilePath);
```suggestion
            Assert.NotNull(specFile.FilePath);
```

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractParameterTest.cs
> +            Assert.NotNull(specFile?.FilePath);
```suggestion
            Assert.NotNull(specFile.FilePath);
```

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractResultTest.cs
> +            Assert.NotNull(specFile?.FilePath);
```suggestion
            Assert.NotNull(specFile.FilePath);
```

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/EndpointControllersTest.cs
> +            Assert.NotNull(specFile?.FilePath);
```suggestion
            Assert.NotNull(specFile.FilePath);
```

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractModelTest.cs
> +    public class ContractModelTest : SyntaxGeneratorTestBase
```suggestion
    public class SyntaxGeneratorContractModelTest : SyntaxGeneratorTestBase
```
and rename filename to match class

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractInterfaceTest.cs
> +    public class ContractInterfaceTest : SyntaxGeneratorTestBase
```suggestion
    public class SyntaxGeneratorContractInterfaceTest : SyntaxGeneratorTestBase
```
and rename filename to match class

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractParameterTest.cs
> +    public class ContractParameterTest : SyntaxGeneratorTestBase
```suggestion
    public class SyntaxGeneratorContractParameterTest : SyntaxGeneratorTestBase
```
and rename filename to match class

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractResultTest.cs
> +    public class ContractResultTest : SyntaxGeneratorTestBase
```suggestion
    public class SyntaxGeneratorContractResultTest : SyntaxGeneratorTestBase
```
and rename filename to match class

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/EndpointControllersTest.cs
> +    public class EndpointControllersTest : SyntaxGeneratorTestBase
```suggestion
    public class SyntaxGeneratorEndpointControllersTest : SyntaxGeneratorTestBase
```
and rename filename to match class

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractInterfaceTest.cs
> +        [Theory(DisplayName = "Contract Interface")]
```suggestion
        [Theory(DisplayName = "Api Contract Interface")]
```
since we also have a ApiClient - then we see the the difference in a test report

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractModelTest.cs
> +        [Theory(DisplayName = "Contract Model")]
```suggestion
        [Theory(DisplayName = "Api Contract Model")]
```
since we also have a ApiClient - then we see the the difference in a test report

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractParameterTest.cs
> +        [Theory(DisplayName = "Contract Parameter")]
```suggestion
        [Theory(DisplayName = "Api Contract Parameter")]
```
since we also have a ApiClient - then we see the the difference in a test report

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractResultTest.cs
> +        [Theory(DisplayName = "Contract Result")]
```suggestion
        [Theory(DisplayName = "Api Contract Result")]
```
since we also have a ApiClient - then we see the the difference in a test report

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/EndpointControllersTest.cs
> +        [Theory(DisplayName = "Contract Controllers")]
```suggestion
        [Theory(DisplayName = "Api Contract Controllers")]
```
since we also have a ApiClient - then we see the the difference in a test report

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/Helpers/CodeGenerator/YamlSpecFile.cs
> +        public string DirectoryName => FileInfo.DirectoryName;
```suggestion
        public string DirectoryName => FileInfo.DirectoryName ?? throw new InvalidOperationException();
```
or make another kind of fallback or just suppress possible null issue with `!`

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/Helpers/CodeGenerator/YamlSpecFile.cs
> +namespace Atc.Rest.ApiGenerator.Tests.Helpers.CodeGenerator
To indicate that this is a test-class-helper, I will suggest the same class-name, but move it to a folder like 'XUnitTestTypes\CodeGenerator' in the project-root

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractInterface/getSimpleInterface.yaml
> +openapi: 3.0.0
To indicate that this is a test-data-file, I will suggest this to be moved into a folder like 'XUnitTestData' to be more clear in seperation of test-files and test-data-files

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractModel/enumComponent.yaml
> +openapi: 3.0.0
To indicate that this is a test-data-file, I will suggest this to be moved into a folder like 'XUnitTestData' to be more clear in seperation of test-files and test-data-files

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractModel/stringComponent.yaml
> +openapi: 3.0.0
To indicate that this is a test-data-file, I will suggest this to be moved into a folder like 'XUnitTestData' to be more clear in seperation of test-files and test-data-files

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractParameter/getWithStringPath.yaml
> +openapi: 3.0.0
To indicate that this is a test-data-file, I will suggest this to be moved into a folder like 'XUnitTestData' to be more clear in seperation of test-files and test-data-files

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractParameter/getWithStringQuery.yaml
> +openapi: 3.0.0
To indicate that this is a test-data-file, I will suggest this to be moved into a folder like 'XUnitTestData' to be more clear in seperation of test-files and test-data-files

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractResult/getOkResponse.yaml
> +openapi: 3.0.0
To indicate that this is a test-data-file, I will suggest this to be moved into a folder like 'XUnitTestData' to be more clear in seperation of test-files and test-data-files

2021-02-09 22:37 UTC, davidkallesen commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/EndpointControllers/getItem.yaml
> +openapi: 3.0.0
To indicate that this is a test-data-file, I will suggest this to be moved into a folder like 'XUnitTestData' to be more clear in seperation of test-files and test-data-files

2021-02-10 05:49 UTC, perkops commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractInterfaceTest.cs
> +namespace Atc.Rest.ApiGenerator.Tests.SyntaxGenerators
Actually all of the files in this folder have an incorrect namespace location.

2021-02-10 05:51 UTC, perkops commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractInterfaceTest.cs
> +            var urlOperation = urlPath.Value.Operations.First();
```suggestion
            var (operationType, openApiOperation) = urlPath.Value.Operations.First();
```

And implement necessary changes below after deconstruction.

2021-02-10 05:52 UTC, perkops commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractModel/enumComponent.yaml.verified.cs
> +        Item2
Theres missing a , after the second item - so something is not generated regarding the newest generator?!

2021-02-10 05:54 UTC, perkops commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractParameterTest.cs
> +            var urlOperation = urlPath.Value.Operations.First();
Use deconstruction here aswell.

2021-02-10 05:54 UTC, perkops commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractParameterTest.cs
> +        public async Task ExecuteGeneratorTest(YamlSpecFile specFile)
No need to use async / await - simply return.

2021-02-10 05:55 UTC, perkops commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractResultTest.cs
> +        public async Task ExecuteGeneratorTest(YamlSpecFile specFile)
No need to use async / await - simply return.

2021-02-10 05:55 UTC, perkops commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/EndpointControllersTest.cs
> +        public async Task ExecuteGeneratorTest(YamlSpecFile specFile)
No need to use async / await - simply return.

2021-02-10 05:55 UTC, perkops commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractInterfaceTest.cs
> +        public async Task ExecuteGeneratorTest(YamlSpecFile specFile)
No need to use async / await - simply return.

2021-02-10 05:55 UTC, perkops commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractModelTest.cs
> +        public async Task ExecuteGeneratorTest(YamlSpecFile specFile)
No need to use async / await - simply return.

2021-02-10 05:56 UTC, perkops commented on test/Atc.Rest.ApiGenerator.Tests/SyntaxGenerators/Api/ContractResultTest.cs
> +            var urlOperation = urlPath.Value.Operations.First();
deconstruction

2021-02-10 17:33 UTC, perkops approved these changes

2021-02-10 20:00 UTC, davidkallesen approved these changes

2021-02-10 20:00 UTC, merged